### ISSUE TITLE
showWithDuration and hideWithDuration

### ISSUE THREAD

**Issue by onepartscissors** [rnystrom/RNBlurModalView#1]
Hi there

Thank you for a fantastic framework, it works great!

One question though, can you show an example of how to use the  showWithDuration and hideWithDuration options?

Thanks,

Ash

**Comment by rnystrom** [comment]
It's exactly similar to using <code>-show</code>. An example:

``` objective-c
RNBlurModalView *modal = [[RNBlurModalView alloc] initWithViewController:self title:@"Hello world!" message:@"Put your message here."];
[modal hideWithDuration:0.3f delay:0 options:UIViewAnimationOptionCurveEaseInOut completion:^{
    // do something on completion
}];
```
