### ISSUE TITLE
Issue with modal view in tableviewcontroller

### ISSUE THREAD

**Issue by instantkaffee** [rnystrom/RNBlurModalView#19]
great library !

if the modal view is triggered in tableview controller when not on top of the table, it shows weird artifact. the label is not entered and the blur is not covering whole tableview.

**Comment by brbgyn** [comment]
Hi instantkaffee,

Have you solved this issue ?

I'm facing the same problem here..

Thank you

**Comment by brbgyn** [comment]
@instantkaffee

**Comment by instantkaffee** [comment]
Done

**Comment by instantkaffee** [comment]
Done
