### ISSUE TITLE
Hi, I have two issues...

### ISSUE THREAD

**Issue by manoelfranklin** [rnystrom/RNBlurModalView#4]
The 1st one is: I'm adding some buttons to the RNBlurModalView... Some of them, from the middle of the screen to the left are normally touchable... The other ones, from the middle to the right are not receiving the touch. It seems that when I touch them, I'm actually touching what is behing, on the parent viewcontroller... How to solve this?

Also, the 2nd one: How can I know when the RNBlurModalView is closed? is there a delegate method? I want to execute some stuff on the parent viewcontroller when the RNBlurModalView is closed. How to do that?

thank you so much!

**Comment by onevcat** [comment]
Cannot catch what you mean by the first issue. But the second one, there is a notification called "kRNBlurDidHidewNotification" (though it is a typo, I think). You can add observer to this notification to get close inform.

**Comment by rnystrom** [comment]
I'm doubting this is an error w/ the control. Closing for now. Post some code if you cannot figure it out and I'll take a peak.
